### ISSUE TITLE
Group list api fails on invalid date format

### ISSUE THREAD

**Issue by TomasVotruba** [php-ug/api.php.ug#1]
I'm using `https://php.ug/api/rest/listtype/1` endpoint to import groups to  https://github.com/tomasvotruba/friendsofphp.org

It worked 2-3 days ago, but now fails on:

```
{"message":"DateInterval::__construct(): Unknown or bad format ()","type":"Exception"}
```

What should I do to fix this? I don't see change anywhere

**Comment by heiglandreas** [comment]
You can report the issue here. Oh wait: You did 👍 

That was due to a dynamic configuration call that didn't have an entry. I've fixed that for now.

So it should work again now. Thanks for reporting!!

**Comment by TomasVotruba** [comment]
Thank you for superfast fix :heart: all works
